### ISSUE TITLE
Steps - initial implementation

### ISSUE THREAD

**Issue by gaviezri** [gaviezri/Stepper#6]
- [x] FileDumper
- [x] CSVExporter
- [x] SpendSomeTime
- [x] CollectFilesInFolder
- [x] FilesDeleter
- [x] FilesRenamer
- [x] FilesContentExtractor
- [x] PropertiesExporter

**Comment by OmriSR** [comment]
OMRI -> FilesContentExtractor
GAL -> PropertiesExporter
